show tables;

select STUDENTNAME, ROUND(STUDENTGPA) 'GPA'
from STUDENT
where STUDENTNAME LIKE '%n%';

SELECT STAFFNAME, round(STAFFPAYRATE, 1) "STAFF PAY RATE"
FROM STAFF
WHERE STAFFPOSITION = 'Tutor';

Select STAFFID, STAFFNAME 'STAFFNAME AND ID'
FROM STAFF
WHERE STAFFPAYRATE >40 and STAFFPAYRATE<70 or STAFFPAYRATE>100;

Select substr(STUDENTNAME, 1,3) 'STUDENT FIRST 3 LETTERS'
FROM STUDENT WHERE STUDENTGPA> 2.5 AND STUDENTGPA<4;

SELECT STUDENTNAME , STUDENTID 
from STUDENT where length(STUDENTNAME)>12;

SELECT COURSEID, COURSENAME, CREDITPOINTS
from COURSE where COURSENAME LIKE '%game of thrones%' and (CREDITPOINTS != 4 or 6);


-- part 2
select COURSEID, STAFFNAME, HoursPerWeek
from  STAFF s, ROSTER r
WHERE r.STAFFID = s.STAFFID;


select COURSEID, STAFFNAME, HOURSPERWEEK
FROM STAFF, ROSTER
WHERE STAFF.STAFFID = ROSTER.STAFFID
AND length(HOURSPERWEEk) = 2;

SELECT COURSEID, R.STAFFID, STAFFNAME
FROM STAFF S , ROSTER R
WHERE S.STAFFID = R.STAFFID 
AND STAFFPOSITION = 'Convenor'
ORDER BY STAFFNAME;

SELECT S.*
FROM STUDENT S ,ENROLMENT E
WHERE S.STUDENTID = E.STUDENTID
AND ENROLDATE >= '1908-15';